services:
  spuc:
    build:
      context: SPUC
      dockerfile: Dockerfile
    image: ghcr.io/uomresearchit/spuc:latest
    container_name: spuc
    ports:
      - "8321:8321"
    volumes:
      - ${PWD}/SPUC/spuc.py /code/spuc.py
      - spuc-output:/code/output
    environment:
      - EXPORT=False

volumes:
  spuc-output:
    name: spuc-output
      
