services:
  spuc:
    build:
      context: SPUC
      dockerfile: Dockerfile
    image: ghcr.io/uomresearchit/spuc:latest
    container_name: spuc
    ports:
      - "8321:80"
    volumes:
      - ${PWD}/SPUC/spuc.py /code/spuc.py
    environment:
      - EXPORT=True
      
